⤵️ automation(synchronize) Applying changes from upstream repository.

diff --git a/.config/taskfiles/ci/Taskfile.yml b/.config/taskfiles/ci/Taskfile.yml
--- a/.config/taskfiles/ci/Taskfile.yml
+++ b/.config/taskfiles/ci/Taskfile.yml
@@ -24,6 +24,8 @@ tasks:
       - pnpm config set store-dir .pnpm-store
 
   checkout:
+    deps:
+      - :install:software:git
     log:
       error: Failed to pull latest changes
       start: Pulling latest changes
@@ -73,12 +75,19 @@ tasks:
     cmds:
       - task: commit:config
       - task: lockfiles:clean
-      - git add --all
+      - |
+        task --list > /dev/null || (echo "ERROR: Invalid Taskfiles!" && exit 1)
+        git add --all
       - git diff --cached "*"
       - |
         if [[ $(git status --porcelain) ]]; then
           git commit -m "⤵️ automation(synchronize) Applying changes from upstream repository."
-          git push -q -o ci.skip origin master
+          git push -q -o ci.skip origin master || FAILED_PUSH=$?
+          if [ -n "$FAILED_PUSH" ]; then
+            git pull origin master
+            task --list &> /dev/null || (echo "ERROR: Invalid Taskfiles!" && exit 1)
+            git push -q -o ci.skip origin master
+          fi
         fi
     status:
       - '[ -z "$CI" ]'
@@ -86,6 +95,7 @@ tasks:
   commit:config:
     deps:
       - :install:software:git
+    run: once
     log:
       error: Error configuring git
       start: Configuring git to use CI-friendly parameters
@@ -94,15 +104,8 @@ tasks:
       - git remote set-url origin "https://root:$GROUP_ACCESS_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git"
       - git config user.email "$GITLAB_CI_EMAIL"
       - git config user.name "$GITLAB_CI_NAME"
-    preconditions:
-      - sh: '[[ ! -z "$GROUP_ACCESS_TOKEN" ]]'
-        msg: The `GROUP_ACCESS_TOKEN` GitLab CI variable must be set to an API key with priviledges to read/write to repositories.
-      - sh: '[[ ! -z "$GITLAB_CI_EMAIL" ]]'
-        msg: 'The `GITLAB_CI_EMAIL` GitLab CI variable must be set to the e-mail address you would like associated with
-          automated commits (e.g. "help@mydomain.com").'
-      - sh: '[[ ! -z "$GITLAB_CI_NAME" ]]'
-        msg: 'The `GITLAB_CI_NAME` GitLab CI variable must be set to the name you would like associated with automated commits
-          (e.g. "CI Automation").'
+    status:
+      - '[ -z "$GROUP_ACCESS_TOKEN" ] || [ -z "$GITLAB_CI_EMAIL" ] || [ -z "$GITLAB_CI_NAME" ] || [ -z "$GITLAB_CI" ]'
 
   lockfiles:
     cmds:
@@ -141,21 +144,29 @@ tasks:
       - '[ -z "$CI" ]'
 
   synchronize:
+    deps:
+      - commit:config
     log:
       error: Failed to update the `synchronize` branch
       start: Synchronizing the `synchronize` branch with the `master` branch
       success: Successfully updated the `synchronize` branch
     cmds:
+      - git fetch origin
       - git checkout -b synchronize || git checkout synchronize
       - git reset --hard HEAD
       - git pull -q origin master
-      - git push -q -o ci.skip origin synchronize --force
       - |
-        if [ '{{.REPOSITORY_TYPE}}' == 'deprecated_common' ] && [ '{{.REPOSITORY_SUBTYPE}}' == 'shared' ]; then
-          .config/log info 'Bypassing the `master` branch pipeline trigger because the repository is not of the right type'
-        else
-          .config/log info 'Triggering the `master` branch pipeline'
-          curl -s --request POST --form "token=${CI_JOB_TOKEN}" --form ref=master --form "variables[PIPELINE_SOURCE]=$PIPELINE_SOURCE" \
-            "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/trigger/pipeline"
+        git push -q -o ci.skip origin synchronize --force || FAILED_SYNC=$?
+        if [ -n "$FAILED_SYNC" ]; then
+          task git:gitlab:protected:off -- "synchronize"
+          git push -q -o ci.skip origin synchronize --force
         fi
+      - task: synchronize:gitlab
       - git checkout master
+
+  synchronize:gitlab:
+    cmds:
+      - curl -s --request POST --form "token=${CI_JOB_TOKEN}" --form ref=master --form "variables[PIPELINE_SOURCE]=$PIPELINE_SOURCE"
+        "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/trigger/pipeline"
+    status:
+      - '[ -z "$GITLAB_CI" ]'
