♻️ refactor(new): newnew

diff --git a/.config/taskfiles/install/Taskfile-python.yml b/.config/taskfiles/install/Taskfile-python.yml
--- a/.config/taskfiles/install/Taskfile-python.yml
+++ b/.config/taskfiles/install/Taskfile-python.yml
@@ -57,15 +57,13 @@ tasks:
       - :install:software:poetry
     run: once
     cmds:
-      - |
-        .config/log info 'Running `poetry install`'
-        if [ '{{.PYTHON_VIRTUALENV}}' != 'true' ]; then
-          poetry config virtualenvs.create false
-        else
-          poetry config --local virtualenvs.in-project true
-        fi
-        poetry install
-        .config/log success '`poetry install` completed successfully'
+      - poetry config virtualenvs.create {{.PYTHON_VIRTUALENV}}
+      - poetry config virtualenvs.in-project true
+      - poetry install
+    log:
+      error: Failed to configure / install via `poetry`
+      start: Configuring Poetry and running `poetry install`
+      success: Successfully ran `poetry install`
     sources:
       - pyproject.toml
     preconditions:
@@ -92,18 +90,24 @@ tasks:
           fi
         fi
 
-  venv:
-    cmds:
-      - if [ ! -d .venv ]; then python3 -m venv .env; fi
-      - |
-        . .venv/bin/activate
-        pip3 install -U pip setuptools
-        pip3 install -r requirements.txt
+  venv:node:
     deps:
       - :install:software:python
+    cmds:
+      - |
+        REQUIREMENTS_PATH="$PWD/requirements.txt"
+        cd "$INIT_CWD" || exit
+        if [ ! -d .venv ]; then
+          python3 -m venv .env
+        else
+          .config/log warn 'The `.venv` folder is already present so a fresh virtualenv cannot be installed'
+        fi
+        . .venv/bin/activate
+        pip3 install -U pip setuptools
+        pip3 install -r "$REQUIREMENTS_PATH"
     log:
       error: Encountered error while setting up `.venv` environment
       start: Setting up a Python 3 `.venv`
-      success: Finished setting up `.venv` - run `. .venv/bin/activate` to load the environment into your shell
+      success: Finished setting up `.venv`. Run `. .venv/bin/activate` to load the environment into your shell.
     sources:
       - requirements.txt
